04-02-2025 09:57:23.756 [pool-3-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:212)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:82)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 09:59:21.835 [pool-5-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:212)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:82)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:11:39.217 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:11:49.686 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:11:53.149 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:11:57.853 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:09.756 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:10.879 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:15.585 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:17.959 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:23.734 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:29.537 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:34.190 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:36.617 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:38.884 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:42.375 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:44.677 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:46.912 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:12:53.969 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:00.914 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:02.085 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:03.234 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:07.921 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:11.470 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:13.765 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:14.901 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:17.131 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:18.252 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:19.443 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:22.949 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:24.081 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:33.628 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:34.774 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:39.534 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:41.839 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:45.333 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:46.513 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:50.027 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:51.242 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:53.633 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:54.795 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:13:58.358 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:00.731 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:03.046 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:05.556 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:06.687 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:07.860 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:10.181 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:11.380 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:14.921 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:16.068 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:19.639 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:23.241 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:25.602 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:26.732 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:27.885 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:29.111 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:33.759 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:34.926 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:36.128 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:37.260 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:37.262 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:38.381 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:39.508 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:40.677 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:41.859 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:44.168 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:46.503 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:48.886 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:50.033 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:52.488 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:53.634 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:55.992 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:57.104 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:14:58.234 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:15:02.828 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:15:04.124 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:15:08.781 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:15:11.163 [pool-4-thread-1] [ERROR] b.Entities.RunningBackups - Error writing to JSON file: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
java.io.FileNotFoundException: src\main\resources\res\config\running_backups.json (The process cannot access the file because it is being used by another process)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:295)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:124)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:67)
	at backupmanager.Entities.RunningBackups.updateBackupsToJSON(RunningBackups.java:119)
	at backupmanager.Entities.RunningBackups.updateBackupToJSON(RunningBackups.java:114)
	at backupmanager.BackupOperations.UpdateProgressPercentage(BackupOperations.java:211)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:78)
	at backupmanager.ZipFileVisitor.visitFile(ZipFileVisitor.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2810)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2881)
	at backupmanager.Services.ZippingThread.lambda$0(ZippingThread.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
04-02-2025 10:32:38.637 [main] [ERROR] backupmanager.MainApp - Argument "--wrong_argument" not valid!
